# ------------------------------------------------------------------------------
# Custom Resource Definitions (CRDs) for Gateway API Inference Extension (GIE)
#
# **Warning**: CRDs are cluster-level, so in a shared development environment
# this needs to be done in a controlled and communicated manner.
# Also used by the coordinator (deploy/coordinator/environments/dev/epd-pools).
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/gateway-api-inference-extension/releases/download/v1.5.0/v1-manifests.yaml
